#! /bin/sh
#
#   Examples build helper
#   Syntax: build all | clean
#
#   This controls whether we get debug or release builds
test -z "$BOOM_MODEL" && BOOM_MODEL=debug

if [ /$1/ = /all/ ]; then
    echo "Building C examples..."
    for MAIN in `egrep -l "main \(" *.c`; do
        echo "$MAIN"
        ./c -l -li ../.. -li ../../jedex/include -li ../include -ll /usr/local/lib -g $MAIN
    done
elif [ /$1/ = /clean/ ]; then
    echo "Cleaning C examples directory..."
    rm -f *.o *.lst core
    for MAIN in `egrep -l "main \(" *.c`; do
        rm -f `basename $MAIN .c`
    done
elif [ -f $1.c ]; then
    echo "$1"
    ./c -v -l -li ../.. -li ../../jedex/include -li ../include -ll /usr/local/lib -g $1
elif [ /$1/ = /lib/ ]; then
  echo "Linking the emirates library..."
    ./c -li ../.. -li ../../jedex/include -li ../include -ll /usr/local/lib -g \
    emirates_main.c
    ./c -li ../.. -li ../../jedex/include -li ../include -ll /usr/local/lib -g -r libemirates \
    emirates_main.c
else
    echo "syntax: build all | clean"
fi
